name: Audit

on:
  push:
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: RSR-Audit token
        id: RSR-Audit
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.RSR_APP_ID }}
          private_key: ${{ secrets.RSR_PRIVATE_KEY }}

      - name: Audit
        uses: reposaur/repo-audit-action@main
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_FULL_TOKEN }}

